/*
  WCS_DB (SQL Server) schema DDL
  - 테이블: ANT_*, MUSHINY_* (INFO / TEMP / HIS)
  - 타입 매핑: NVARCHAR2 -> NVARCHAR, NUMERIC 10 -> NUMERIC(10,0), DECIMAL 13,4 -> DECIMAL(13,4), DATETIME -> DATETIME2(3)
  - REPORT_TIME: NVARCHAR(100) (요청 명세 준수). 필요 시 BIGINT(ms) 또는 DATETIME2 로 변경 가능
  - 기본 스키마: dbo
*/

/* ========== ANT_ROBOT_INFO ========== */
IF OBJECT_ID('dbo.ANT_ROBOT_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_ROBOT_INFO (
        ROBOT_NO       NVARCHAR(30)  NOT NULL,
        ROBOT_TYPE     NVARCHAR(30)  NULL,
        MAP_CODE       NVARCHAR(30)  NULL,
        ZONE_CODE      NVARCHAR(100) NULL,
        STATUS         NUMERIC(10,0) NULL,
        MANUAL         NVARCHAR(10)  NULL,
        LOADERS        NVARCHAR(100) NULL,
        REPORT_TIME    NVARCHAR(100) NULL,
        BATTERY        DECIMAL(13,4) NULL,
        NODE_ID        NVARCHAR(100) NULL,
        POS_X          DECIMAL(13,4) NULL,
        POS_Y          DECIMAL(13,4) NULL,
        SPEED          DECIMAL(13,4) NULL,
        TASK_ID        NVARCHAR(100) NULL,
        NEXT_TARGET    NVARCHAR(100) NULL,
        POD_ID         NVARCHAR(100) NULL,
        INS_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_ROBOT_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID    NVARCHAR(15)  NULL,
        UPD_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_ROBOT_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID    NVARCHAR(15)  NULL,
        UUID           NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_ROBOT_INFO PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_ROBOT_INFO_UUID ON dbo.ANT_ROBOT_INFO(UUID);
    CREATE INDEX IX_ANT_ROBOT_INFO_REPORT_TIME ON dbo.ANT_ROBOT_INFO(REPORT_TIME);
END
GO

/* ========== ANT_INV_INFO ========== */
IF OBJECT_ID('dbo.ANT_INV_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_INV_INFO (
        INVENTORY      NVARCHAR(100) NOT NULL,
        BATCH_NUM      NVARCHAR(100) NULL,
        UNITLOAD       NVARCHAR(100) NULL,
        SKU            NVARCHAR(100) NULL,
        PRE_QTY        NUMERIC(10,0) NULL,
        NEW_QTY        NUMERIC(10,0) NULL,
        ORIGIN_ORDER   NVARCHAR(100) NULL,
        STATUS         NUMERIC(10,0) NULL,
        REPORT_TIME    NVARCHAR(100) NULL,
        INS_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_INV_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID    NVARCHAR(15)  NULL,
        UPD_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_INV_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID    NVARCHAR(15)  NULL,
        UUID           NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_INV_INFO PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_INV_INFO_UUID ON dbo.ANT_INV_INFO(UUID);
    CREATE INDEX IX_ANT_INV_INFO_REPORT_TIME ON dbo.ANT_INV_INFO(REPORT_TIME);
END
GO

/* ========== ANT_POD_INFO ========== */
IF OBJECT_ID('dbo.ANT_POD_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_POD_INFO (
        POD_ID         NVARCHAR(100) NOT NULL,
        POD_FACE       NVARCHAR(100) NULL,
        LOCATION       NVARCHAR(100) NULL,
        REPORT_TIME    NVARCHAR(100) NULL,
        INS_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_POD_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID    NVARCHAR(15)  NULL,
        UPD_DT         DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_POD_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID    NVARCHAR(15)  NULL,
        UUID           NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_POD_INFO PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_POD_INFO_UUID ON dbo.ANT_POD_INFO(UUID);
    CREATE INDEX IX_ANT_POD_INFO_REPORT_TIME ON dbo.ANT_POD_INFO(REPORT_TIME);
END
GO

/* ========== MUSHINY_AGV_INFO ========== */
IF OBJECT_ID('dbo.MUSHINY_AGV_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_AGV_INFO (
        ROBOT_NO        NVARCHAR(30)  NOT NULL,
        ZONE_CODE       NVARCHAR(100) NULL,
        NODE_ID         NVARCHAR(100) NULL,
        DIRECTION_FRONT NVARCHAR(10)  NULL,
        POD_ID          NVARCHAR(100) NULL,
        POD_DIRECTION   NVARCHAR(10)  NULL,
        STATUS          NUMERIC(10,0) NULL,
        MANUAL          NVARCHAR(10)  NULL,
        BATTERY         DECIMAL(13,4) NULL,
        POS_X           DECIMAL(13,4) NULL,
        POS_Y           DECIMAL(13,4) NULL,
        HAS_POD         NVARCHAR(10)  NULL,
        INS_DT          DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_AGV_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID     NVARCHAR(15)  NULL,
        UPD_DT          DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_AGV_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID     NVARCHAR(15)  NULL,
        UUID            NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_AGV_INFO PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_AGV_INFO_UUID ON dbo.MUSHINY_AGV_INFO(UUID);
END
GO

/* ========== MUSHINY_POD_INFO ========== */
IF OBJECT_ID('dbo.MUSHINY_POD_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_POD_INFO (
        POD_ID        NVARCHAR(100) NOT NULL,
        SECTION_ID    NUMERIC(10,0) NOT NULL,
        ZONE_CODE     NVARCHAR(100) NULL,
        LOCATION      NVARCHAR(100) NULL,
        POD_DIRECTION NVARCHAR(10)  NULL,
        POS_X         DECIMAL(13,4) NULL,
        POS_Y         DECIMAL(13,4) NULL,
        INS_DT        DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_POD_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID   NVARCHAR(15)  NULL,
        UPD_DT        DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_POD_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID   NVARCHAR(15)  NULL,
        UUID          NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_POD_INFO PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_POD_INFO_UUID ON dbo.MUSHINY_POD_INFO(UUID);
END
GO

/* ========== TEMP 테이블들 (수신 임시) ========== */
IF OBJECT_ID('dbo.ANT_ROBOT_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_ROBOT_INFO_TEMP (
        ROBOT_NO    NVARCHAR(30)  NOT NULL,
        ROBOT_TYPE  NVARCHAR(30)  NULL,
        MAP_CODE    NVARCHAR(30)  NULL,
        ZONE_CODE   NVARCHAR(100) NULL,
        STATUS      NUMERIC(10,0) NULL,
        MANUAL      NVARCHAR(10)  NULL,
        LOADERS     NVARCHAR(100) NULL,
        REPORT_TIME NVARCHAR(100) NULL,
        BATTERY     DECIMAL(13,4) NULL,
        NODE_ID     NVARCHAR(100) NULL,
        POS_X       DECIMAL(13,4) NULL,
        POS_Y       DECIMAL(13,4) NULL,
        SPEED       DECIMAL(13,4) NULL,
        TASK_ID     NVARCHAR(100) NULL,
        NEXT_TARGET NVARCHAR(100) NULL,
        POD_ID      NVARCHAR(100) NULL,
        INS_DT      DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_RBT_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID NVARCHAR(15)  NULL,
        UPD_DT      DATETIME2(3)  NULL,
        UPD_USER_ID NVARCHAR(15)  NULL,
        UUID        NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_ROBOT_INFO_TEMP PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_ROBOT_INFO_TMP_UUID ON dbo.ANT_ROBOT_INFO_TEMP(UUID);
END
GO

IF OBJECT_ID('dbo.ANT_INV_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_INV_INFO_TEMP (
        INVENTORY   NVARCHAR(100) NOT NULL,
        BATCH_NUM   NVARCHAR(100) NULL,
        UNITLOAD    NVARCHAR(100) NULL,
        SKU         NVARCHAR(100) NULL,
        PRE_QTY     NUMERIC(10,0) NULL,
        NEW_QTY     NUMERIC(10,0) NULL,
        ORIGIN_ORDER NVARCHAR(100) NULL,
        STATUS      NUMERIC(10,0) NULL,
        REPORT_TIME NVARCHAR(100) NULL,
        INS_DT      DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_INV_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID NVARCHAR(15)  NULL,
        UPD_DT      DATETIME2(3)  NULL,
        UPD_USER_ID NVARCHAR(15)  NULL,
        UUID        NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_INV_INFO_TEMP PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_INV_INFO_TMP_UUID ON dbo.ANT_INV_INFO_TEMP(UUID);
END
GO

IF OBJECT_ID('dbo.ANT_POD_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_POD_INFO_TEMP (
        POD_ID      NVARCHAR(100) NOT NULL,
        POD_FACE    NVARCHAR(100) NULL,
        LOCATION    NVARCHAR(100) NULL,
        REPORT_TIME NVARCHAR(100) NULL,
        INS_DT      DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_POD_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID NVARCHAR(15)  NULL,
        UPD_DT      DATETIME2(3)  NULL,
        UPD_USER_ID NVARCHAR(15)  NULL,
        UUID        NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_POD_INFO_TEMP PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_POD_INFO_TMP_UUID ON dbo.ANT_POD_INFO_TEMP(UUID);
END
GO

IF OBJECT_ID('dbo.MUSHINY_AGV_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_AGV_INFO_TEMP (
        ROBOT_NO        NVARCHAR(30)  NOT NULL,
        ZONE_CODE       NVARCHAR(100) NULL,
        NODE_ID         NVARCHAR(100) NULL,
        DIRECTION_FRONT NVARCHAR(10)  NULL,
        POD_ID          NVARCHAR(100) NULL,
        POD_DIRECTION   NVARCHAR(10)  NULL,
        STATUS          NUMERIC(10,0) NULL,
        MANUAL          NVARCHAR(10)  NULL,
        BATTERY         DECIMAL(13,4) NULL,
        POS_X           DECIMAL(13,4) NULL,
        POS_Y           DECIMAL(13,4) NULL,
        HAS_POD         NVARCHAR(10)  NULL,
        INS_DT          DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_AGV_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID     NVARCHAR(15)  NULL,
        UPD_DT          DATETIME2(3)  NULL,
        UPD_USER_ID     NVARCHAR(15)  NULL,
        UUID            NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_AGV_INFO_TEMP PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_AGV_INFO_TMP_UUID ON dbo.MUSHINY_AGV_INFO_TEMP(UUID);
END
GO

IF OBJECT_ID('dbo.MUSHINY_POD_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_POD_INFO_TEMP (
        POD_ID        NVARCHAR(100) NOT NULL,
        SECTION_ID    NUMERIC(10,0) NULL,
        ZONE_CODE     NVARCHAR(100) NULL,
        LOCATION      NVARCHAR(100) NULL,
        POD_DIRECTION NVARCHAR(10)  NULL,
        POS_X         DECIMAL(13,4) NULL,
        POS_Y         DECIMAL(13,4) NULL,
        INS_DT        DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_POD_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID   NVARCHAR(15)  NULL,
        UPD_DT        DATETIME2(3)  NULL,
        UPD_USER_ID   NVARCHAR(15)  NULL,
        UUID          NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_POD_INFO_TEMP PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_POD_INFO_TMP_UUID ON dbo.MUSHINY_POD_INFO_TEMP(UUID);
END
GO

/* ========== HIS 테이블들 (수신 이력) ========== */
IF OBJECT_ID('dbo.ANT_ROBOT_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_ROBOT_INFO_HIS (
        ID           BIGINT IDENTITY(1,1) NOT NULL,
        ROBOT_NO     NVARCHAR(30)  NULL,
        ROBOT_TYPE   NVARCHAR(30)  NULL,
        MAP_CODE     NVARCHAR(30)  NULL,
        ZONE_CODE    NVARCHAR(100) NULL,
        STATUS       NUMERIC(10,0) NULL,
        MANUAL       NVARCHAR(10)  NULL,
        LOADERS      NVARCHAR(100) NULL,
        REPORT_TIME  NVARCHAR(100) NULL,
        BATTERY      DECIMAL(13,4) NULL,
        NODE_ID      NVARCHAR(100) NULL,
        POS_X        DECIMAL(13,4) NULL,
        POS_Y        DECIMAL(13,4) NULL,
        SPEED        DECIMAL(13,4) NULL,
        TASK_ID      NVARCHAR(100) NULL,
        NEXT_TARGET  NVARCHAR(100) NULL,
        POD_ID       NVARCHAR(100) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_RBT_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NULL,
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL
    ,
        CONSTRAINT PK_ANT_ROBOT_INFO_HIS PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_ROBOT_INFO_HIS_UUID ON dbo.ANT_ROBOT_INFO_HIS(UUID);
    CREATE INDEX IX_ANT_ROBOT_INFO_HIS_REPORT_TIME ON dbo.ANT_ROBOT_INFO_HIS(REPORT_TIME);
END
GO

IF OBJECT_ID('dbo.ANT_INV_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_INV_INFO_HIS (
        ID           BIGINT IDENTITY(1,1) NOT NULL,
        INVENTORY    NVARCHAR(100) NULL,
        BATCH_NUM    NVARCHAR(100) NULL,
        UNITLOAD     NVARCHAR(100) NULL,
        SKU          NVARCHAR(100) NULL,
        PRE_QTY      NUMERIC(10,0) NULL,
        NEW_QTY      NUMERIC(10,0) NULL,
        ORIGIN_ORDER NVARCHAR(100) NULL,
        STATUS       NUMERIC(10,0) NULL,
        REPORT_TIME  NVARCHAR(100) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_INV_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NULL,
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_INV_INFO_HIS PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_INV_INFO_HIS_UUID ON dbo.ANT_INV_INFO_HIS(UUID);
    CREATE INDEX IX_ANT_INV_INFO_HIS_REPORT_TIME ON dbo.ANT_INV_INFO_HIS(REPORT_TIME);
END
GO

IF OBJECT_ID('dbo.ANT_POD_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_POD_INFO_HIS (
        ID           BIGINT IDENTITY(1,1) NOT NULL,
        POD_ID       NVARCHAR(100) NULL,
        POD_FACE     NVARCHAR(100) NULL,
        LOCATION     NVARCHAR(100) NULL,
        REPORT_TIME  NVARCHAR(100) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_POD_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NULL,
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_POD_INFO_HIS PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_ANT_POD_INFO_HIS_UUID ON dbo.ANT_POD_INFO_HIS(UUID);
    CREATE INDEX IX_ANT_POD_INFO_HIS_REPORT_TIME ON dbo.ANT_POD_INFO_HIS(REPORT_TIME);
END
GO

IF OBJECT_ID('dbo.MUSHINY_AGV_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_AGV_INFO_HIS (
        ID              BIGINT IDENTITY(1,1) NOT NULL,
        ROBOT_NO        NVARCHAR(30)  NULL,
        ZONE_CODE       NVARCHAR(100) NULL,
        NODE_ID         NVARCHAR(100) NULL,
        DIRECTION_FRONT NVARCHAR(10)  NULL,
        POD_ID          NVARCHAR(100) NULL,
        POD_DIRECTION   NVARCHAR(10)  NULL,
        STATUS          NUMERIC(10,0) NULL,
        MANUAL          NVARCHAR(10)  NULL,
        BATTERY         DECIMAL(13,4) NULL,
        POS_X           DECIMAL(13,4) NULL,
        POS_Y           DECIMAL(13,4) NULL,
        HAS_POD         NVARCHAR(10)  NULL,
        INS_DT          DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_AGV_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID     NVARCHAR(15)  NULL,
        UPD_DT          DATETIME2(3)  NULL,
        UPD_USER_ID     NVARCHAR(15)  NULL,
        UUID            NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_AGV_INFO_HIS PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_AGV_INFO_HIS_UUID ON dbo.MUSHINY_AGV_INFO_HIS(UUID);
END
GO

IF OBJECT_ID('dbo.MUSHINY_POD_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.MUSHINY_POD_INFO_HIS (
        ID           BIGINT IDENTITY(1,1) NOT NULL,
        POD_ID       NVARCHAR(100) NULL,
        SECTION_ID   NUMERIC(10,0) NULL,
        ZONE_CODE    NVARCHAR(100) NULL,
        LOCATION     NVARCHAR(100) NULL,
        POD_DIRECTION NVARCHAR(10) NULL,
        POS_X        DECIMAL(13,4) NULL,
        POS_Y        DECIMAL(13,4) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_MSH_POD_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NULL,
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_MUSHINY_POD_INFO_HIS PRIMARY KEY CLUSTERED (UUID)
    );
    CREATE UNIQUE INDEX UX_MUSHINY_POD_INFO_HIS_UUID ON dbo.MUSHINY_POD_INFO_HIS(UUID);
END
GO

/* ========== ANT_FLYPICK_INFO (및 TEMP/HIS) ========== */
IF OBJECT_ID('dbo.ANT_FLYPICK_INFO','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_FLYPICK_INFO (
        ROBOT_NO     NVARCHAR(30)  NOT NULL,
        ROBOT_TYPE   NVARCHAR(30)  NULL,
        MAP_CODE     NVARCHAR(30)  NULL,
        ZONE_CODE    NVARCHAR(100) NULL,
        STATUS       NUMERIC(10,0) NULL,
        MANUAL       NVARCHAR(10)  NULL,
        REPORT_TIME  NVARCHAR(100) NULL,
        BATTERY      DECIMAL(13,4) NULL,
        NODE_ID      NVARCHAR(100) NULL,
        POS_X        DECIMAL(13,4) NULL,
        POS_Y        DECIMAL(13,4) NULL,
        SPEED        DECIMAL(13,4) NULL,
        TASK_ID      NVARCHAR(100) NULL,
        NEXT_TARGET  NVARCHAR(100) NULL,
        POD_ID       NVARCHAR(100) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_FLYPICK_INFO_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_FLYPICK_INFO_UPD_DT DEFAULT (SYSDATETIME()),
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_FLYPICK_INFO PRIMARY KEY CLUSTERED (ROBOT_NO)
    );
    CREATE UNIQUE INDEX UX_ANT_FLYPICK_INFO_UUID ON dbo.ANT_FLYPICK_INFO(UUID);
END
GO

IF OBJECT_ID('dbo.ANT_FLYPICK_INFO_TEMP','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_FLYPICK_INFO_TEMP (
        ROBOT_NO     NVARCHAR(30)  NOT NULL,
        ROBOT_TYPE   NVARCHAR(30)  NULL,
        MAP_CODE     NVARCHAR(30)  NULL,
        ZONE_CODE    NVARCHAR(100) NULL,
        STATUS       NUMERIC(10,0) NULL,
        MANUAL       NVARCHAR(10)  NULL,
        REPORT_TIME  NVARCHAR(100) NULL,
        BATTERY      DECIMAL(13,4) NULL,
        NODE_ID      NVARCHAR(100) NULL,
        POS_X        DECIMAL(13,4) NULL,
        POS_Y        DECIMAL(13,4) NULL,
        SPEED        DECIMAL(13,4) NULL,
        TASK_ID      NVARCHAR(100) NULL,
        NEXT_TARGET  NVARCHAR(100) NULL,
        POD_ID       NVARCHAR(100) NULL,
        INS_DT       DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_FLYPICK_TMP_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID  NVARCHAR(15)  NULL,
        UPD_DT       DATETIME2(3)  NULL,
        UPD_USER_ID  NVARCHAR(15)  NULL,
        UUID         NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_ANT_FLYPICK_INFO_TEMP PRIMARY KEY CLUSTERED (ROBOT_NO)
    );
    CREATE UNIQUE INDEX UX_ANT_FLYPICK_INFO_TMP_UUID ON dbo.ANT_FLYPICK_INFO_TEMP(UUID);
END
GO

IF OBJECT_ID('dbo.ANT_FLYPICK_INFO_HIS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ANT_FLYPICK_INFO_HIS (
        ID          BIGINT IDENTITY(1,1) PRIMARY KEY,
        ROBOT_NO    NVARCHAR(30)  NULL,
        ROBOT_TYPE  NVARCHAR(30)  NULL,
        MAP_CODE    NVARCHAR(30)  NULL,
        ZONE_CODE   NVARCHAR(100) NULL,
        STATUS      NUMERIC(10,0) NULL,
        MANUAL      NVARCHAR(10)  NULL,
        REPORT_TIME NVARCHAR(100) NULL,
        BATTERY     DECIMAL(13,4) NULL,
        NODE_ID     NVARCHAR(100) NULL,
        POS_X       DECIMAL(13,4) NULL,
        POS_Y       DECIMAL(13,4) NULL,
        SPEED       DECIMAL(13,4) NULL,
        TASK_ID     NVARCHAR(100) NULL,
        NEXT_TARGET NVARCHAR(100) NULL,
        POD_ID      NVARCHAR(100) NULL,
        INS_DT      DATETIME2(3)  NOT NULL CONSTRAINT DF_ANT_FLYPICK_HIS_INS_DT DEFAULT (SYSDATETIME()),
        INS_USER_ID NVARCHAR(15)  NULL,
        UPD_DT      DATETIME2(3)  NULL,
        UPD_USER_ID NVARCHAR(15)  NULL,
        UUID        NVARCHAR(100) NOT NULL
    );
    CREATE UNIQUE INDEX UX_ANT_FLYPICK_INFO_HIS_UUID ON dbo.ANT_FLYPICK_INFO_HIS(UUID);
END
GO

/* ========== VIEW 골격 (스키마만 정의, 데이터는 추후) ========== */
IF OBJECT_ID('dbo.MC_STA_MST_VIEW','V') IS NOT NULL DROP VIEW dbo.MC_STA_MST_VIEW;
GO
CREATE VIEW dbo.MC_STA_MST_VIEW AS
SELECT
    CAST(NULL AS NVARCHAR(7))  AS MC_TYP,
    CAST(NULL AS NVARCHAR(10)) AS MC_NO,
    CAST(NULL AS NVARCHAR(7))  AS MC_AREA_TYP,
    CAST(NULL AS NVARCHAR(50)) AS MC_NM,
    CAST(NULL AS NVARCHAR(30)) AS ERROR_CODE
WHERE 1 = 0;
GO

IF OBJECT_ID('dbo.CAPA_HOUR_VIEW','V') IS NOT NULL DROP VIEW dbo.CAPA_HOUR_VIEW;
GO
CREATE VIEW dbo.CAPA_HOUR_VIEW AS
SELECT
    CAST(NULL AS NVARCHAR(10)) AS TIME,
    CAST(NULL AS NUMERIC(10,0)) AS QTY
WHERE 1 = 0;
GO

IF OBJECT_ID('dbo.CAPA_DAY_VIEW','V') IS NOT NULL DROP VIEW dbo.CAPA_DAY_VIEW;
GO
CREATE VIEW dbo.CAPA_DAY_VIEW AS
SELECT
    CAST(NULL AS NVARCHAR(10)) AS TIME,
    CAST(NULL AS NUMERIC(10,0)) AS QTY
WHERE 1 = 0;
GO

IF OBJECT_ID('dbo.ZONE_RATE_VIEW','V') IS NOT NULL DROP VIEW dbo.ZONE_RATE_VIEW;
GO
CREATE VIEW dbo.ZONE_RATE_VIEW AS
SELECT
    CAST(NULL AS NVARCHAR(30)) AS ZONE_CD,
    CAST(NULL AS NUMERIC(10,0)) AS RATE,
    CAST(NULL AS NUMERIC(10,0)) AS QTY
WHERE 1 = 0;
GO

IF OBJECT_ID('dbo.FLOOR_RATE_VIEW','V') IS NOT NULL DROP VIEW dbo.FLOOR_RATE_VIEW;
GO
CREATE VIEW dbo.FLOOR_RATE_VIEW AS
SELECT
    CAST(NULL AS NVARCHAR(30)) AS ZONE_CD,
    CAST(NULL AS NVARCHAR(7))  AS FLOOR,
    CAST(NULL AS NUMERIC(10,0)) AS RATE,
    CAST(NULL AS NUMERIC(10,0)) AS QTY
WHERE 1 = 0;
GO 